name: CD pointeuse

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - shell: bash
      run: chmod +x resetService.sh
    - shell: bash
      run: chmod +x hello.py
    - shell: bash
      run: ./resetService.sh
